import Head from "next/head";
import AppBar from "../components/appBar/AppBar";
import Instructions from "../components/register/Instructions";
import RegisterForm from "../components/register/RegisterForm";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Coin Registery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen flex items-center justify-center mt-20 space-x-16">
        <Instructions
          title="Instruction"
          text="If you have already registered don't need to enter name,dep,reg num again"
        />
        <RegisterForm />
        <Instructions
          title="Modify Status"
          text="If you want to modify the status enter your reg no or faculty id and the status"
        />
      </main>
    </div>
  );
}
