import { Button, CircularProgress } from "@mui/material";
import axios from "axios";
import Head from "next/head";
import React, { useEffect, useRef, useState } from "react";
import RegisterForm from "../components/register/RegisterForm";

export default function Home() {
  const [auth, setAuth] = useState<boolean>(false);
  const [pass, setPass] = useState<string>("");

  useEffect(() => {
    const p = window.localStorage.getItem("password");

    if (p === "admin@coin") {
      setAuth(true);
    }
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPass(e.target.value);
  };

  const verifyPassword = (e: React.SyntheticEvent) => {
    e.preventDefault();

    if (pass === "admin@coin") {
      window.localStorage.setItem("password", pass);

      setAuth(true);
    }
  };

  return (
    <div className="">
      <Head>
        <title>Coin Registery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen flex items-center justify-center mt-20 space-x-16">
        {/* qrcode  */}
        {auth ? (
          <>
            <RegisterForm />
          </>
        ) : (
          <section className="p-4 shadow-lg mb-6">
            <form className="space-x-3" onSubmit={verifyPassword}>
              <input
                onChange={handleChange}
                className="border py-1 px-2"
                placeholder="Password"
                type="password"
              />

              <Button variant="outlined" size="small">
                Submit
              </Button>
            </form>
          </section>
        )}
      </main>
    </div>
  );
}
